# Generated by Django 5.1.2 on 2024-11-18 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='content',
        ),
    ]
