# Generated by Django 5.1.3 on 2024-11-18 13:18

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 18, 13, 18, 51, 564161, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TagFollow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_follows', to='blog_app.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_follows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='followers',
            field=models.ManyToManyField(related_name='followed_tags', through='blog_app.TagFollow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['slug'], name='blog_app_ta_slug_dd1e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='blog_app_ta_name_35ebca_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['-created_at'], name='blog_app_ta_created_9721dc_idx'),
        ),
        migrations.AddIndex(
            model_name='tagfollow',
            index=models.Index(fields=['user', 'tag'], name='blog_app_ta_user_id_397783_idx'),
        ),
        migrations.AddIndex(
            model_name='tagfollow',
            index=models.Index(fields=['created_at'], name='blog_app_ta_created_504da2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tagfollow',
            unique_together={('user', 'tag')},
        ),
    ]
