# Generated by Django 5.1.2 on 2024-11-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
