# Generated by Django 5.1.3 on 2024-11-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0003_notification_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='session_key',
        ),
    ]
